module.exports = {
    BIRTH_CERTIFICATE: "BIRTH_CERTIFICATE",
    DRIVERS_LICENSE: "DRIVERS_LICENSE",
    PASSPORT: "PASSPORT",
    PROOF_OF_ADDRESS: "PROOF_OF_ADDRESS",
    SOCIAL_SECURITY: "SOCIAL_SECURITY",
    STATE_ID: "STATE_ID"
};
